// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cytjsuhorotxckidykec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dGpzdWhvcm90eGNraWR5a2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjAwNDIsImV4cCI6MjA2MDIzNjA0Mn0.BFx2Qf0iwP29q7KSvRnsJ5qTobJNhObacKjIG0gl8-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);